export const CACHE = {
  PRODUCTS: 'PRODUCTS',
  PRODUCT: 'PRODUCT',
  CART_HISTORY: 'CART_HISTORY',
  CART: 'CART',
  HISTORIES: 'HISTORIES',
  HISTORY: 'HISTORY',
  MEMBERS: 'MEMBERS',
  MEMBER: 'MEMBER',
  REPORTS: 'REPORTS',
} as const;
